### ISSUE TITLE
Mislabelling of person in Comments field

### ISSUE THREAD

**Issue by KenLWalker** [Bowerbird/bowerbird-web#36]
Hi,

I have just been alerted to an interesting problem.

It appears that when someone leaves a Comment to an existing Observation, that the avatar and name used is that of the originator of the Observation rather than the different person who left the Comment.

This problem does not appear when someone uses the Notes method to leave a comment on an existing Observation.

Ken

**Comment by frankradocaj** [comment]
Can you give an example? I can't seem to replicate it.

**Comment by KenLWalker** [comment]
Hi,

I only saw it once and I cannot find that occurrence now.

I have not seen it happen again – it all seems very stable now.

Cheers,

Ken

**Comment by frankradocaj** [comment]
Ok, no problem. I'll close the issue. If it happens again, we can re-open it then.
