### ISSUE TITLE
Identify and Describe buttons not working

### ISSUE THREAD

**Issue by KenLWalker** [Bowerbird/bowerbird-web#37]
Strangely, the top Identify and Describe button work well:

![2013-03-19_1115](https://f.cloud.github.com/assets/3622867/273558/51ca771e-902a-11e2-8204-a62b609cdc62.png).

However, similar buttons below do not work:

![2013-03-19_1118](https://f.cloud.github.com/assets/3622867/273564/89a5894e-902a-11e2-8dd8-7b74ef18be2d.png)

Can the code for the top button be replicated for the bottom buttons?

Ken

**Comment by frankradocaj** [comment]
Fixed.
