### ISSUE TITLE
Taxonomy module buttons not visible

### ISSUE THREAD

**Issue by KenLWalker** [Bowerbird/bowerbird-web#38]
Some laptop users are reporting they cannot see or reach the CANCEL or DONE button for the pop up taxonomy module.

Here is a screen grab from one of these users:

![2013-03-19_1123](https://f.cloud.github.com/assets/3622867/273589/4e7a13de-902b-11e2-97f4-939294c2bca8.png)

Would it be possible to locate the popup at the Top of the screen rather than the middle of the screen?  That may enable them to see and use these buttons.

Ken

**Comment by frankradocaj** [comment]
As per discussion, press F11 on very small screens. I have also pushed the popup close to the top of the screen to avoid the problem in most cases.

**Comment by KenLWalker** [comment]
Very cool! And thanks
