### ISSUE TITLE
Identification votes are not saving

### ISSUE THREAD

**Issue by KenLWalker** [Bowerbird/bowerbird-web#40]
I have voted for one of the identifications at least 10 times and while it shows my vote when I click it when I reopen the record it shows no votes.

![2013-03-19_1435](https://f.cloud.github.com/assets/3622867/274025/35eb09ca-9046-11e2-85dd-15e6f50c27c9.png)

**Comment by frankradocaj** [comment]
Fixed. Issue was with sightings containing more than one identification/description.
