### ISSUE TITLE
Voting system not working

### ISSUE THREAD

**Issue by KenLWalker** [Bowerbird/bowerbird-web#47]
Vote for identifications do not appear to be working, Here is an example of where I incorrectly identified a moth.  Another person came along and created a new and correct identification which I voted for several days ago.  That vote has now been lost.

![2013-04-24_1703](https://f.cloud.github.com/assets/3622867/418564/4fc82c3c-acad-11e2-9ac5-13c4a1a982bd.png)

**Comment by frankradocaj** [comment]
Duplicate issue. Fixed.
