### ISSUE TITLE
Two "Load more" button at bottom at Projects screen

### ISSUE THREAD

**Issue by KenLWalker** [Bowerbird/bowerbird-web#51]
Frank -- I think you said this bug may be related to the sorting bug where no returns happen when you try to sort the Projects from A-Z

![2013-04-29_0958](https://f.cloud.github.com/assets/3622867/436633/e9dfd4cc-b05f-11e2-9224-420891491bea.png)

**Comment by frankradocaj** [comment]
Fixed, new infinite scrolling no longer requires load more button.

**Comment by KenLWalker** [comment]
I saw that and it’s great!
